version: '3.8'
services:
  mysql-attendance:
     image: mysql:8.0
     cap_add:
      - SYS_NICE
     restart: always
     environment:
      - MYSQL_DATABASE=attendance
      - MYSQL_ROOT_PASSWORD=12345678
     ports:
      - '3305:3306'
     volumes:
      - mysql-attendance:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql-attendance:
    driver: local